### ISSUE TITLE
Tema del Sitio

### ISSUE THREAD

**Issue by jandres4444** [saldana83/clubdeleones#1]
- Falta elegir el tema del sitio de acuerdo a los requerimientos establecidos en cuanto a diseño y elección de los colores.

-AL CREAR UNA PAGINA NUEVA, TENER EL CUIDADO DE ELEGIR EL TEMA ASIGNADO (default.htm)

**Comment by saldana83** [comment]
Mi sitio local ahora no me esta cargando. Me dice problemas con el theme..

**Comment by jandres4444** [comment]
INFORMACIÓN: Anteriormente se ha tenido inconvenientes con el cms, ocurre por las actualizaciones que se le han hecho a la base de datos y cambios internos. 

POSIBLES SOLUCIONES:
-Asegurarse de que disponga de la última actualización vista desde gitcraken o en github
-Clonar nuevamente el repositorio desde github para así tener la última versión del sistema
